// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peripherals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedEvent = `-- name: CreateFeedEvent :one
INSERT INTO feed_events (
    event_type, control_id, user_name, description
) VALUES (
    $1, $2, $3, $4
) RETURNING id, event_type, control_id, user_name, description, created_at
`

type CreateFeedEventParams struct {
	EventType   FeedEventType `json:"event_type"`
	ControlID   pgtype.Text   `json:"control_id"`
	UserName    string        `json:"user_name"`
	Description pgtype.Text   `json:"description"`
}

// 「誰が何を更新したか」をタイムラインに流すためのクエリです
func (q *Queries) CreateFeedEvent(ctx context.Context, arg CreateFeedEventParams) (FeedEvent, error) {
	row := q.db.QueryRow(ctx, createFeedEvent,
		arg.EventType,
		arg.ControlID,
		arg.UserName,
		arg.Description,
	)
	var i FeedEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ControlID,
		&i.UserName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedEvents = `-- name: ListFeedEvents :many
SELECT id, event_type, control_id, user_name, description, created_at FROM feed_events
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListFeedEvents(ctx context.Context) ([]FeedEvent, error) {
	rows, err := q.db.Query(ctx, listFeedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedEvent
	for rows.Next() {
		var i FeedEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ControlID,
			&i.UserName,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingUnmatchedTasks = `-- name: ListPendingUnmatchedTasks :many
SELECT id, original_file_name, row_number, question_text, status, created_at, resolved_at FROM unmatched_tasks
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingUnmatchedTasks(ctx context.Context) ([]UnmatchedTask, error) {
	rows, err := q.db.Query(ctx, listPendingUnmatchedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnmatchedTask
	for rows.Next() {
		var i UnmatchedTask
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFileName,
			&i.RowNumber,
			&i.QuestionText,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
