// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateControl(ctx context.Context, arg CreateControlParams) (Control, error)
	DeleteControl(ctx context.Context, id string) error
	// backend/db/query/controls.sql
	GetControl(ctx context.Context, id string) (GetControlRow, error)
	LinkControlTag(ctx context.Context, arg LinkControlTagParams) error
	ListControls(ctx context.Context) ([]ListControlsRow, error)
	ListFeedEvents(ctx context.Context) ([]FeedEvent, error)
	ListPendingUnmatchedTasks(ctx context.Context) ([]UnmatchedTask, error)
	// 指定されたキーワード（$1）が、タイトル・質問・回答のどこかに含まれる Control を検索します
	SearchControls(ctx context.Context, dollar_1 pgtype.Text) ([]Control, error)
	UpdateControl(ctx context.Context, arg UpdateControlParams) (Control, error)
	UpsertTag(ctx context.Context, name string) (int32, error)
}

var _ Querier = (*Queries)(nil)
