// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchControls = `-- name: SearchControls :many
SELECT id, title, category, question, answer, status, version, created_at, updated_at FROM controls
WHERE (title || ' ' || question || ' ' || answer) ILIKE '%' || $1 || '%'
ORDER BY updated_at DESC
`

// 指定されたキーワード（$1）が、タイトル・質問・回答のどこかに含まれる Control を検索します
func (q *Queries) SearchControls(ctx context.Context, dollar_1 pgtype.Text) ([]Control, error) {
	rows, err := q.db.Query(ctx, searchControls, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Control
	for rows.Next() {
		var i Control
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
